name: ci
on: [push,pull_request]
jobs:
  test:
    name: Java ${{ matrix.java }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        java:
          - '18'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
